version: '3'
services:
    nextjs:
        build: 
            context: ./next-app
            dockerfile: Dockerfile
    nginx:
        build:
            context: ./nginx
            dockerfile: Dockerfile
        ports:
            - 80:80