version: '3'
services:
    nextjs:
        build: 
            context: ./next-app
            dockerfile: Dockerfile
        ports: 
            - 3000:3000
    nginx:
        build:
            context: ./nginx
            dockerfile: Dockerfile
        ports:
            - 8000:8000